Fork of Tk used in the "Little" project. http://www.mcvoy.com/lm/little/index.html

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -9845,7 +9845,7 @@ echo "${ECHO_T}couldn't find any!" >&6
 	echo "$as_me:$LINENO: checking for X11 libraries" >&5
 echo $ECHO_N "checking for X11 libraries... $ECHO_C" >&6
 	XLIBSW=nope
-	dirs="/usr/unsupported/lib /usr/local/lib /usr/X386/lib /usr/X11R6/lib /usr/X11R5/lib /usr/lib/X11R5 /usr/lib/X11R4 /usr/openwin/lib /usr/X11/lib /usr/sww/X11/lib"
+	dirs="/usr/unsupported/lib /usr/local/lib /usr/X386/lib /usr/X11R6/lib /usr/X11R5/lib /usr/lib/X11R6 /usr/lib/X11R5 /usr/lib/X11R4 /usr/openwin/lib /usr/X11/lib /usr/sww/X11/lib"
 	for i in $dirs ; do
 	    if test -r $i/libX11.a -o -r $i/libX11.so -o -r $i/libX11.sl -o -r $i/libX11.dylib; then
 		echo "$as_me:$LINENO: result: $i" >&5
@@ -10151,7 +10151,7 @@ echo "${ECHO_T}$enable_xft" >&6
 	if test "$found_xft" = "no" ; then
 	    found_xft=yes
 	    XFT_CFLAGS=`pkg-config --cflags xft 2>/dev/null` || found_xft="no"
-	    XFT_LIBS=`pkg-config --libs xft 2>/dev/null` || found_xft="no"
+	    XFT_LIBS=`pkg-config --libs xft fontconfig 2>/dev/null` || found_xft="no"
 	fi
 	echo "$as_me:$LINENO: result: $found_xft" >&5
 echo "${ECHO_T}$found_xft" >&6
@@ -10386,8 +10386,9 @@ fi
 	fi
 		if test "$found_xft" = "no" ; then
 	    if test "$enable_xft" = "yes" ; then
-		{ echo "$as_me:$LINENO: WARNING: Can't find xft configuration, or xft is unusable" >&5
-echo "$as_me: WARNING: Can't find xft configuration, or xft is unusable" >&2;}
+		{ { echo "$as_me:$LINENO: error: Can't find xft configuration, or xft is unusable" >&5
+echo "$as_me: error: Can't find xft configuration, or xft is unusable" >&2;}
+   { (exit 1); exit 1; }; }
 	    fi
 	    enable_xft=no
 	    XFT_CFLAGS=""
