Force kill exit code to be zero, and make error message more specific.

diff --git a/.github/workflows/mac-build.yml b/.github/workflows/mac-build.yml
--- a/.github/workflows/mac-build.yml
+++ b/.github/workflows/mac-build.yml
@@ -119,7 +119,7 @@ jobs:
               Xvfb $1 &
               XVFB_PID=$!
               echo Launched Xvfb $1 as process $XVFB_PID >&2
-              trap "echo killing process $XVFB_PID... >&2; kill $XVFB_PID; exit $?" 0
+              trap "echo killing process $XVFB_PID... >&2; kill $XVFB_PID; exit 0" 0
               export DISPLAY=$1
               sleep 2
             }
@@ -133,7 +133,7 @@ jobs:
             exit 1
           }
           cat out.txt | grep -q "Failed	[1-9]" && {
-            echo "::error::Failure during Test"
+            echo "::error::Failure in test results"
             exit 1
           }
       - name: Carry out trial installation
