Revert the logic of grepping in the output file because we need an exit code of 0 for grep. As a consequence we need to grep separately in each (classic and ttk) output file. Finally restore proper killing of xvfb.

diff --git a/.github/workflows/mac-build.yml b/.github/workflows/mac-build.yml
--- a/.github/workflows/mac-build.yml
+++ b/.github/workflows/mac-build.yml
@@ -118,6 +118,7 @@ jobs:
               Xvfb $1 &
               XVFB_PID=$!
               echo Launched Xvfb $1 as process $XVFB_PID >&2
+              trap "echo killing process $XVFB_PID... >&2; kill $XVFB_PID" 0
               export DISPLAY=$1
               sleep 2
             }
@@ -126,12 +127,20 @@ jobs:
               echo Xvfb not used, this is a --enable-aqua build
             }
           fi
-          ( runXvfb :0; make test-classic test-ttk; exit $? ) | tee out.txt || {
-            echo "::error::Failure during Test"
+          ( runXvfb :0; make test-classic; exit $? ) | tee out-classic.txt || {
+            echo "::error::Failure during Test (classic)"
             exit 1
           }
-          cat out.txt | grep -q "Failed	[1-9]" && {
-            echo "::error::Failure in test results"
+          ( runXvfb :0; make test-ttk; exit $? ) | tee out-ttk.txt || {
+            echo "::error::Failure during Test (ttk)"
+            exit 1
+          }
+          cat out-classic.txt | grep -q "Failed	0" || {
+            echo "::error::Failure in classic test results"
+            exit 1
+          }
+          cat out-ttk.txt | grep -q "Failed	0" || {
+            echo "::error::Failure in ttk test results"
             exit 1
           }
       - name: Carry out trial installation
