Backport some "github actions" improvements from 8.6

diff --git a/.github/workflows/win-build.yml b/.github/workflows/win-build.yml
--- a/.github/workflows/win-build.yml
+++ b/.github/workflows/win-build.yml
@@ -60,7 +60,11 @@ jobs:
             echo "::error::Failure during Test"
             exit 1
           }
-          cat out-classic.txt out-ttk.txt | grep -q "Failed	[1-9]" && {
+          grep -q "Failed	0" out-classic.txt || {
+            echo "::error::Failure during Test"
+            exit 1
+          }
+          grep -q "Failed	0" out-ttk.txt || {
             echo "::error::Failure during Test"
             exit 1
           }
@@ -141,8 +145,13 @@ jobs:
           }
       - name: Run Tests
         run: |
-          make test-classic | tee out-classic.txt || echo "::error::Failure during Test"
-          make test-ttk | tee out-ttk.txt || echo "::error::Failure during Test"
-          cat out-classic.txt out-ttk.txt | grep -q "Failed	[1-9]" && {
+          make test-classic | tee out-classic.txt
+          make test-ttk | tee out-ttk.txt
+          grep -q "Failed	0" out-classic.txt || {
             echo "::error::Failure during Test"
+            exit 1
+          }
+          grep -q "Failed	0" out-ttk.txt || {
+            echo "::error::Failure during Test"
+            exit 1
           }
